@startuml

entity Tank{
    id: UUID,
    name: Str,
    available_volume: double,
    current_volume: double,
}
entity Tanker{
    id: UUID,
    name: str,
}
entity Difference{
    id: UUID,
    value: doulbe,
    type: DifferenceType,
    tank_id: UUID,
    tanker_id: UUID,
}

Tank --|{ Difference
Tanker --o{ Difference
@enduml