@startuml
skinparam linetype ortho

entity Tank{
    id: Str,
    name: Str,
    available_volume: double,
    current_volume: double,
    previous_volume: double,
    safe_volume: double,
    vessel_id: Str,
}
enum DifferenceType{
    Bunkering,
    Consumption,
}
entity Difference{
    id: UUID,
    volume: doulbe,
    mass: doulbe,
    type: DifferenceType,
    tank_id: UUID,
}
entity Vessel{
    id: UUID,
    name: Str,
}
entity Consumer{
    id: UUID,
    name: Str,
    type: ConsumerType,
    vessel_id: UUID,
}
enum ConsumerType{
    Engine,
    Generator,
}

Difference }|-|| Tank
Tank }|-|| Vessel
Difference ||-down-|| DifferenceType
Consumer ||--|| ConsumerType
Vessel ||--|{ Consumer
@enduml